<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HSGalaxy.Core\HSGalaxy.Core.csproj" />
  </ItemGroup>

  <!-- Remove heavy Azure package; we use lightweight HTTP client to call REST API -->

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

