<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\HSGalaxy.Core\HSGalaxy.Core.csproj" />
    <ProjectReference Include="..\HSGalaxy.Diagnostics\HSGalaxy.Diagnostics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.6.2" />
    <PackageReference Include="Vortice.DirectComposition" Version="3.6.2" />
    <PackageReference Include="Vortice.DXGI" Version="3.6.2" />
    <PackageReference Include="Vortice.Mathematics" Version="1.9.2" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.6.2" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
